DATASET:
  AUGMENTATION:
    augment: true
    gamma_lower: -0.5
    gamma_upper: 0.6
    mean_noise: 0.004357355181127787
    std_noise: 0.02553257718682289
    x_deg: 0
    y_deg: 0
    z_deg: 25
  artifacts:
  - 7
  axial_steps: 1
  batch_size: 32
  ex_autofluorescence: false
  ex_melanocytes: true
  exp: +s_+d_-f
  folds: 4
  lateral_steps: 512
  mean: 0.004357355181127787
  remove_artifacts: false
  std: 0.02553257718682289
  x_patch: 512
  y_patch: 512
  z_patch: 1
MODEL:
  channel_layers:
  - 64
  - 128
  - 256
  - 512
  - 1024
  dropout: 0.15
  input_dim: 1
  l2: 0.00421
  learning_rate: 7.54e-05
  model_arch: UNET
  norm: batch
  num_res_units: 2
  spatial_dim: 2
  strides:
  - 2
  - 2
  - 2
  - 2
RESULTS:
  log_file_path: /home/jsfung/projects/def-haas/jsfung/results/ResUNet/20230305/1_512_512_+s_+d_-f/091822_log_fold
  model_states_path: /home/jsfung/projects/def-haas/jsfung/results/ResUNet/20230305/1_512_512_+s_+d_-f/+s_+d_-f_2D_ResUNet_175.pth
TRAINING:
  shuffle: true
date: '20230305_091822'
end_cycle: 20
loss: dice_ce
mask_path: /home/jsfung/projects/def-haas/jsfung/Images/new_labels/Mask/*.tif
max_epochs: 200
model_name: ResUNet
parent_dir: /home/haas/projects/def-haas/jsfung
raw_path: /home/jsfung/projects/def-haas/jsfung/Images/new_labels/Raw/*.tif
weights: null
